spring:
  application:
    name: spring-modulith-lab
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.freefeather: DEBUG